# Generated by Django 3.0.3 on 2020-10-05 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketeers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.FileField(upload_to='router_specifications'),
        ),
    ]
