# Generated by Django 3.0.3 on 2020-10-05 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketeers', '0006_auto_20201005_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.CharField(max_length=100),
        ),
    ]
