# Generated by Django 3.0.3 on 2020-10-05 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketeers', '0007_auto_20201005_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='image',
            field=models.FileField(upload_to='\\static\\marketeers\\images\\Client'),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.FileField(upload_to='\\static\\marketeers\\images\\Events'),
        ),
        migrations.AlterField(
            model_name='team',
            name='image',
            field=models.FileField(upload_to='\\static\\marketeers\\images\\Team'),
        ),
    ]
